# Generated by Django 6.0.4 on 2026-04-15 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_idea', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('dormant', 'Aguardando feedback'), ('completed', 'Concluído'), ('paused', 'Pausado pelo Controller')], default='active', max_length=20)),
                ('github_repo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_issue_number', models.IntegerField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('labels', models.JSONField(default=list)),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Você'), ('po', 'Product Owner'), ('pm', 'Project Manager'), ('el', 'Engineering Lead'), ('dev1', 'Developer (Frontend)'), ('dev2', 'Developer (Backend)'), ('system', 'Sistema')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('cc', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='projects.emailmessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('po', 'Product Owner'), ('pm', 'Project Manager'), ('el', 'Engineering Lead'), ('dev1', 'Developer (Frontend)'), ('dev2', 'Developer (Backend)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('blocked', 'Bloqueado')], default='pending', max_length=20)),
                ('last_concern', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'persona')},
            },
        ),
    ]
