# Generated by Django 6.0.4 on 2026-04-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_repo',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Você'), ('po', 'Product Owner'), ('fc', 'Entrevistador de Campo'), ('el', 'Engineering Lead'), ('dev1', 'Developer (Frontend)'), ('dev2', 'Developer (Backend)'), ('system', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personastate',
            name='persona',
            field=models.CharField(choices=[('po', 'Product Owner'), ('fc', 'Entrevistador de Campo'), ('el', 'Engineering Lead'), ('dev1', 'Developer (Frontend)'), ('dev2', 'Developer (Backend)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('ui', 'Spec de UI'), ('backend', 'Spec de Backend'), ('business', 'Business & Requisitos'), ('technical', 'Especificação Técnica')], max_length=20)),
                ('version_type', models.CharField(choices=[('full', 'Especificação Completa'), ('delta', 'Delta — Alterações')], default='full', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='projects.project')),
            ],
            options={
                'ordering': ['version', 'spec_type'],
            },
        ),
        migrations.DeleteModel(
            name='GitHubIssue',
        ),
    ]
