# Generated by Django 6.0.4 on 2026-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_github_repo_alter_emailmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_activity',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
