# Generated by Django 6.0.4 on 2026-04-15 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, max_length=200)),
                ('github_token', models.CharField(blank=True, max_length=200)),
                ('github_default_repo', models.CharField(blank=True, max_length=200)),
                ('max_tokens_per_project', models.IntegerField(default=100000)),
                ('max_cost_usd_per_project', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('controller_check_every_n_tokens', models.IntegerField(default=5000)),
                ('max_rounds_per_flow', models.IntegerField(default=20)),
                ('auto_create_github_issues', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
